install: 
- bash get-NDK.sh
- bash get-ACE-TAO.sh
- bash get-OpenDDS.sh
script:
- bash configure.sh
- bash build.sh
matrix:
  include:
# r18b
    - name: "arm-r18b-16"
      env:
        - arch=arm
        - ndk=r18b
        - api=16
    - name: "arm-r18b-21"
      env:
        - arch=arm
        - ndk=r18b
        - api=21
    - name: "arm-r18b-24"
      env:
        - arch=arm
        - ndk=r18b
        - api=24
    - name: "arm-r18b-28"
      env:
        - arch=arm
        - ndk=r18b
        - api=28
# r17c
    - name: "arm-r17c-16"
      env:
        - arch=arm
        - ndk=r17c
        - api=16
    - name: "arm-r17c-21"
      env:
        - arch=arm
        - ndk=r17c
        - api=21
    - name: "arm-r17c-24"
      env:
        - arch=arm
        - ndk=r17c
        - api=24
    - name: "arm-r17c-28"
      env:
        - arch=arm
        - ndk=r17c
        - api=28
# r16b
    - name: "arm-r16b-16"
      env:
        - arch=arm
        - ndk=r16b
        - api=16
    - name: "arm-r16b-21"
      env:
        - arch=arm
        - ndk=r16b
        - api=21
    - name: "arm-r16b-24"
      env:
        - arch=arm
        - ndk=r16b
        - api=24
# r12b
    - name: "arm-r12b-16"
      env:
        - arch=arm
        - ndk=r12b
        - api=16
    - name: "arm-r12b-21"
      env:
        - arch=arm
        - ndk=r12b
        - api=21
    - name: "arm-r12b-24"
      env:
        - arch=arm
        - ndk=r12b
        - api=24
