set -e

header="# File generated by mk_matrix.sh"

# Travis Jobs
cat << END > .travis.yml
$header
install:
- bash get-NDK.sh
- bash mk_toolchain.sh
- bash get-ACE-TAO.sh
- bash get-OpenDDS.sh
script:
- bash configure.sh
- bash build.sh
matrix:
  include:
END
python3 matrix.py travis >> .travis.yml

# Shell Equivalent
cat <<END > shell_matrix.sh
$header
set -e

END
python3 matrix.py shell >> shell_matrix.sh
