set -e

bash get_ace_tao.sh
bash get_opendds.sh
bash get_xerces.sh
bash get_openssl.sh

# BEGIN MATRIX
# This part is generated by matrix.py
# r21 ========================================
ndk=r21 bash get_ndk.sh
echo r21-arm-16
ndk=r21 arch=arm api=16 bash single_round.sh &> r21-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-17
ndk=r21 arch=arm api=17 bash single_round.sh &> r21-arm-17.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-18
ndk=r21 arch=arm api=18 bash single_round.sh &> r21-arm-18.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-19
ndk=r21 arch=arm api=19 bash single_round.sh &> r21-arm-19.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-21
ndk=r21 arch=arm api=21 bash single_round.sh &> r21-arm-21.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-22
ndk=r21 arch=arm api=22 bash single_round.sh &> r21-arm-22.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-23
ndk=r21 arch=arm api=23 bash single_round.sh &> r21-arm-23.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-24
ndk=r21 arch=arm api=24 bash single_round.sh &> r21-arm-24.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-26
ndk=r21 arch=arm api=26 bash single_round.sh &> r21-arm-26.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-27
ndk=r21 arch=arm api=27 bash single_round.sh &> r21-arm-27.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-28
ndk=r21 arch=arm api=28 bash single_round.sh &> r21-arm-28.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm-29
ndk=r21 arch=arm api=29 bash single_round.sh &> r21-arm-29.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-arm64-29
ndk=r21 arch=arm64 api=29 bash single_round.sh &> r21-arm64-29.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r21-x86_64-29
ndk=r21 arch=x86_64 api=29 bash single_round.sh &> r21-x86_64-29.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r21 bash rm_ndk.sh
# r20b ========================================
ndk=r20b bash get_ndk.sh
echo r20b-arm-16
ndk=r20b arch=arm api=16 bash single_round.sh &> r20b-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r20b-arm-28
ndk=r20b arch=arm api=28 bash single_round.sh &> r20b-arm-28.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r20b-arm-29
ndk=r20b arch=arm api=29 bash single_round.sh &> r20b-arm-29.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r20b bash rm_ndk.sh
# r19c ========================================
ndk=r19c bash get_ndk.sh
echo r19c-arm-16
ndk=r19c arch=arm api=16 bash single_round.sh &> r19c-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r19c-arm-28
ndk=r19c arch=arm api=28 bash single_round.sh &> r19c-arm-28.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r19c bash rm_ndk.sh
# r18b ========================================
ndk=r18b bash get_ndk.sh
echo r18b-arm-16
ndk=r18b arch=arm api=16 bash single_round.sh &> r18b-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r18b-arm-28
ndk=r18b arch=arm api=28 bash single_round.sh &> r18b-arm-28.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r18b bash rm_ndk.sh
# r17c ========================================
ndk=r17c bash get_ndk.sh
echo r17c-arm-16
ndk=r17c arch=arm api=16 bash single_round.sh &> r17c-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r17c-arm-24
ndk=r17c arch=arm api=24 bash single_round.sh &> r17c-arm-24.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r17c-arm-28
ndk=r17c arch=arm api=28 bash single_round.sh &> r17c-arm-28.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r17c bash rm_ndk.sh
# r15c ========================================
ndk=r15c bash get_ndk.sh
echo r15c-arm-16
ndk=r15c arch=arm api=16 bash single_round.sh &> r15c-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r15c-arm-21
ndk=r15c arch=arm api=21 bash single_round.sh &> r15c-arm-21.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r15c-arm-24
ndk=r15c arch=arm api=24 bash single_round.sh &> r15c-arm-24.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r15c bash rm_ndk.sh
# r14b ========================================
ndk=r14b bash get_ndk.sh
echo r14b-arm-16
ndk=r14b arch=arm api=16 bash single_round.sh &> r14b-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
echo r14b-arm-21
ndk=r14b arch=arm api=21 bash single_round.sh &> r14b-arm-21.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r14b bash rm_ndk.sh
# r12b ========================================
ndk=r12b bash get_ndk.sh
echo r12b-arm-16
ndk=r12b arch=arm api=16 bash single_round.sh &> r12b-arm-16.log || (echo FAIL; bash rm_toolchain.sh; exit 0)
ndk=r12b bash rm_ndk.sh
# END MATRIX
