name: matrix

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 3 * * 5"

jobs:
  matrix:
    runs-on: ubuntu-18.04

    # TODO: Figure out a way let the matrix cases define the environment variables
    env:
      name: ${{ matrix.name }}
      arch: ${{ matrix.arch }}
      ndk: ${{ matrix.ndk }}
      api: ${{ matrix.api }}
      use_toolchain: ${{ matrix.use_toolchain }}
      ace_tao: ${{ matrix.ace_tao }}
      use_security: ${{ matrix.use_security }}
      use_java: ${{ matrix.use_java }}

    steps:
    - uses: actions/checkout@v2

    - name: Print the Equivalent settings.sh
      # For for Quickly Reproducing Failing CI Builds
      run: |
        bash print_settings.sh

    - name: Get NDK
      run: |
        bash get_ndk.sh
        bash get_toolchain.sh

    - name: Get OpenDDS and Dependencies
      run: |
        bash get_ace_tao.sh
        bash get_opendds.sh
        if ${use_security:-false}; then bash get_xerces.sh; fi
        if ${use_security:-false}; then bash get_openssl.sh; fi

    - name: Build
      run: |
        bash configure.sh
        bash build.sh

    strategy:
      fail-fast: false
      matrix:
        include:
# BEGIN MATRIX
# This part is generated by matrix.py
# doc_group_master ===============================================================
# r21d ---------------------------------------------------------------------------
          - name: r21d-arm64-29-security-java-doc-group-master
            arch: arm64
            ndk: r21d
            api: 29
            use_security: true
            use_java: true
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-28-doc-group-master
            arch: arm64
            ndk: r21d
            api: 28
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-27-doc-group-master
            arch: arm64
            ndk: r21d
            api: 27
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-26-doc-group-master
            arch: arm64
            ndk: r21d
            api: 26
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-24-doc-group-master
            arch: arm64
            ndk: r21d
            api: 24
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-23-doc-group-master
            arch: arm64
            ndk: r21d
            api: 23
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-22-doc-group-master
            arch: arm64
            ndk: r21d
            api: 22
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-21-doc-group-master
            arch: arm64
            ndk: r21d
            api: 21
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm-19-doc-group-master
            arch: arm
            ndk: r21d
            api: 19
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm-18-doc-group-master
            arch: arm
            ndk: r21d
            api: 18
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm-17-doc-group-master
            arch: arm
            ndk: r21d
            api: 17
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm-16-security-java-doc-group-master
            arch: arm
            ndk: r21d
            api: 16
            use_security: true
            use_java: true
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r21d-arm64-29-toolchain-doc-group-master
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_master"
# r22-beta1 ----------------------------------------------------------------------
          - name: r22-beta1-arm64-30-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 30
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-29-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 29
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-28-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 28
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-27-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 27
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-26-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 26
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-24-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 24
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-23-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 23
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-22-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 22
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm64-21-doc-group-master
            arch: arm64
            ndk: r22-beta1
            api: 21
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm-19-doc-group-master
            arch: arm
            ndk: r22-beta1
            api: 19
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm-18-doc-group-master
            arch: arm
            ndk: r22-beta1
            api: 18
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm-17-doc-group-master
            arch: arm
            ndk: r22-beta1
            api: 17
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r22-beta1-arm-16-doc-group-master
            arch: arm
            ndk: r22-beta1
            api: 16
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
# r20b ---------------------------------------------------------------------------
          - name: r20b-arm64-29-doc-group-master
            arch: arm64
            ndk: r20b
            api: 29
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r20b-arm-16-doc-group-master
            arch: arm
            ndk: r20b
            api: 16
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
# r19c ---------------------------------------------------------------------------
          - name: r19c-arm64-28-doc-group-master
            arch: arm64
            ndk: r19c
            api: 28
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
          - name: r19c-arm-16-doc-group-master
            arch: arm
            ndk: r19c
            api: 16
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_master"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm64-28-toolchain-doc-group-master
            arch: arm64
            ndk: r18b
            api: 28
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_master"
          - name: r18b-arm-16-toolchain-doc-group-master
            arch: arm
            ndk: r18b
            api: 16
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_master"
# doc_group_ace6_tao2 ============================================================
# r21d ---------------------------------------------------------------------------
          - name: r21d-arm64-29-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-28-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 28
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-27-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 27
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-26-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 26
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-24-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 24
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-23-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 23
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-22-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 22
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-21-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 21
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm-19-doc-group-ace6-tao2
            arch: arm
            ndk: r21d
            api: 19
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm-18-doc-group-ace6-tao2
            arch: arm
            ndk: r21d
            api: 18
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm-17-doc-group-ace6-tao2
            arch: arm
            ndk: r21d
            api: 17
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm-16-doc-group-ace6-tao2
            arch: arm
            ndk: r21d
            api: 16
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r21d-arm64-29-toolchain-doc-group-ace6-tao2
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_ace6_tao2"
# r19c ---------------------------------------------------------------------------
          - name: r19c-arm64-28-doc-group-ace6-tao2
            arch: arm64
            ndk: r19c
            api: 28
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
          - name: r19c-arm-16-doc-group-ace6-tao2
            arch: arm
            ndk: r19c
            api: 16
            use_security: false
            use_java: false
            use_toolchain: false
            ace_tao: "doc_group_ace6_tao2"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm64-28-toolchain-doc-group-ace6-tao2
            arch: arm64
            ndk: r18b
            api: 28
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_ace6_tao2"
          - name: r18b-arm-16-toolchain-doc-group-ace6-tao2
            arch: arm
            ndk: r18b
            api: 16
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_ace6_tao2"
# r12b ---------------------------------------------------------------------------
          - name: r12b-arm64-24-toolchain-doc-group-ace6-tao2
            arch: arm64
            ndk: r12b
            api: 24
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_ace6_tao2"
          - name: r12b-arm-16-toolchain-doc-group-ace6-tao2
            arch: arm
            ndk: r12b
            api: 16
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "doc_group_ace6_tao2"
# oci ============================================================================
# r21d ---------------------------------------------------------------------------
          - name: r21d-arm64-29-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-28-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 28
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-27-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 27
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-26-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 26
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-24-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 24
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-23-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 23
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-22-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 22
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-21-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 21
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm-19-toolchain-oci
            arch: arm
            ndk: r21d
            api: 19
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm-18-toolchain-oci
            arch: arm
            ndk: r21d
            api: 18
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm-17-toolchain-oci
            arch: arm
            ndk: r21d
            api: 17
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm-16-toolchain-oci
            arch: arm
            ndk: r21d
            api: 16
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
          - name: r21d-arm64-29-toolchain-oci
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_toolchain: true
            ace_tao: "oci"
