name: matrix

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 5"

jobs:
  matrix:
    runs-on: ubuntu-18.04

    # TODO: Figure out a way let the matrix cases define the environment variables
    env:
      name: ${{ matrix.name }}
      arch: ${{ matrix.arch }}
      ndk: ${{ matrix.ndk }}
      api: ${{ matrix.api }}
      use_security: ${{ matrix.use_security }}
      use_java: ${{ matrix.use_java }}
      use_oci_ace_tao: ${{ matrix.use_oci_ace_tao }}

    steps:
    - uses: actions/checkout@v2

    - name: Get NDK
      run: |
        bash get_ndk.sh
        bash mk_toolchain.sh

    - name: Get OpenDDS and Dependencies
      run: |
        bash get_ace_tao.sh
        bash get_opendds.sh
        if ${use_security:-false}; then bash get_xerces.sh; fi
        if ${use_security:-false}; then bash get_openssl.sh; fi

    - name: Build
      run: |
        bash configure.sh
        bash build.sh

    strategy:
      fail-fast: false
      matrix:
        include:
# BEGIN MATRIX
# This part is generated by matrix.py
# r22-beta1 ========================================
          - name: r22-beta1-arm64-30-security-java
            arch: arm64
            ndk: r22-beta1
            api: 30
            use_security: true
            use_java: true
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-29
            arch: arm64
            ndk: r22-beta1
            api: 29
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-28
            arch: arm64
            ndk: r22-beta1
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-27
            arch: arm64
            ndk: r22-beta1
            api: 27
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-26
            arch: arm64
            ndk: r22-beta1
            api: 26
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-24
            arch: arm64
            ndk: r22-beta1
            api: 24
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-23
            arch: arm64
            ndk: r22-beta1
            api: 23
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-22
            arch: arm64
            ndk: r22-beta1
            api: 22
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm64-21
            arch: arm64
            ndk: r22-beta1
            api: 21
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm-19
            arch: arm
            ndk: r22-beta1
            api: 19
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm-18
            arch: arm
            ndk: r22-beta1
            api: 18
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm-17
            arch: arm
            ndk: r22-beta1
            api: 17
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r22-beta1-arm-16-security-java
            arch: arm
            ndk: r22-beta1
            api: 16
            use_security: true
            use_java: true
            use_oci_ace_tao: false
# r21d ========================================
          - name: r21d-arm64-29-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 29
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-28-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-27-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 27
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-26-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 26
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-24-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 24
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-23-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 23
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-22-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 22
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm64-21-oci-ace-tao
            arch: arm64
            ndk: r21d
            api: 21
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm-19-oci-ace-tao
            arch: arm
            ndk: r21d
            api: 19
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm-18-oci-ace-tao
            arch: arm
            ndk: r21d
            api: 18
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm-17-oci-ace-tao
            arch: arm
            ndk: r21d
            api: 17
            use_security: false
            use_java: false
            use_oci_ace_tao: true
          - name: r21d-arm-16-oci-ace-tao
            arch: arm
            ndk: r21d
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: true
# r20b ========================================
          - name: r20b-arm64-29
            arch: arm64
            ndk: r20b
            api: 29
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r20b-arm64-28
            arch: arm64
            ndk: r20b
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r20b-arm-16
            arch: arm
            ndk: r20b
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r19c ========================================
          - name: r19c-arm64-28
            arch: arm64
            ndk: r19c
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r19c-arm-16
            arch: arm
            ndk: r19c
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r18b ========================================
          - name: r18b-arm64-28
            arch: arm64
            ndk: r18b
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r18b-arm-16
            arch: arm
            ndk: r18b
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r17c ========================================
          - name: r17c-arm64-28
            arch: arm64
            ndk: r17c
            api: 28
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r17c-arm64-27
            arch: arm64
            ndk: r17c
            api: 27
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r17c-arm64-26
            arch: arm64
            ndk: r17c
            api: 26
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r17c-arm-16
            arch: arm
            ndk: r17c
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r15c ========================================
          - name: r15c-arm64-26
            arch: arm64
            ndk: r15c
            api: 26
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r15c-arm64-24
            arch: arm64
            ndk: r15c
            api: 24
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r15c-arm-16
            arch: arm
            ndk: r15c
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r14b ========================================
          - name: r14b-arm64-24
            arch: arm64
            ndk: r14b
            api: 24
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r14b-arm-16
            arch: arm
            ndk: r14b
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
# r12b ========================================
          - name: r12b-arm64-24
            arch: arm64
            ndk: r12b
            api: 24
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r12b-arm64-21
            arch: arm64
            ndk: r12b
            api: 21
            use_security: false
            use_java: false
            use_oci_ace_tao: false
          - name: r12b-arm-16
            arch: arm
            ndk: r12b
            api: 16
            use_security: false
            use_java: false
            use_oci_ace_tao: false
