name: matrix

on:
  push:
    branches:
      - '*'
      - '!macos'
  schedule:
    - cron: "0 3 * * 5"
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ${{ matrix.os }}

    # TODO: Figure out a way let the matrix cases define the environment variables
    env:
      name: ${{ matrix.name }}
      arch: ${{ matrix.arch }}
      ndk: ${{ matrix.ndk }}
      api: ${{ matrix.api }}
      use_toolchain: ${{ matrix.use_toolchain }}
      ace_tao: ${{ matrix.ace_tao }}
      use_security: ${{ matrix.use_security }}
      use_java: ${{ matrix.use_java }}
      target_api: ${{ matrix.target_api }}

    steps:
    - uses: actions/checkout@v4

    - name: Print the Equivalent settings.sh
      # For Quickly Reproducing Failing CI Builds
      run: |
        bash print_settings.sh

    - name: Get NDK and Toolchain
      run: |
        bash get_ndk.sh
        bash get_toolchain.sh

    - name: Get SDK
      if: ${{ matrix.use_java }}
      run: |
        bash get_sdk.sh

    - name: Get Xerces
      if: ${{ matrix.use_security }}
      run: |
        bash get_xerces.sh

    - name: Get OpenSSL
      if: ${{ matrix.use_security }}
      run: |
        bash get_openssl.sh

    - name: Get ACE/TAO and OpenDDS
      run: |
        bash get_ace_tao.sh
        bash get_opendds.sh

    - name: Configure and Build Xerces
      if: ${{ matrix.use_security }}
      run: |
        bash build_xerces.sh

    - name: Configure and Build OpenSSL
      if: ${{ matrix.use_security }}
      run: |
        bash build_openssl.sh

    - name: Configure ACE/TAO and OpenDDS
      run: bash configure.sh

    - name: Build ACE/TAO and OpenDDS
      run: bash build.sh

    strategy:
      fail-fast: false
      matrix:
        include:
# BEGIN MATRIX
# This part is generated by matrix.py
# doc_group_master ===============================================================
# r23b ---------------------------------------------------------------------------
          - name: r23b-arm64-30-security-java-doc-group-master
            arch: arm64
            ndk: r23b
            api: 30
            os: "ubuntu-22.04"
            use_security: true
            use_java: true
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-29-doc-group-master
            arch: arm64
            ndk: r23b
            api: 29
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-28-doc-group-master
            arch: arm64
            ndk: r23b
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-27-doc-group-master
            arch: arm64
            ndk: r23b
            api: 27
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-26-doc-group-master
            arch: arm64
            ndk: r23b
            api: 26
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-24-doc-group-master
            arch: arm64
            ndk: r23b
            api: 24
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-23-doc-group-master
            arch: arm64
            ndk: r23b
            api: 23
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-22-doc-group-master
            arch: arm64
            ndk: r23b
            api: 22
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-21-doc-group-master
            arch: arm64
            ndk: r23b
            api: 21
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-20-doc-group-master
            arch: arm
            ndk: r23b
            api: 20
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-19-doc-group-master
            arch: arm
            ndk: r23b
            api: 19
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-18-doc-group-master
            arch: arm
            ndk: r23b
            api: 18
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-17-doc-group-master
            arch: arm
            ndk: r23b
            api: 17
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-16-security-java-doc-group-master
            arch: arm
            ndk: r23b
            api: 16
            os: "ubuntu-22.04"
            use_security: true
            use_java: true
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm64-30-doc-group-master
            arch: arm64
            ndk: r23b
            api: 30
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23b-arm-16-doc-group-master
            arch: arm
            ndk: r23b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r22b ---------------------------------------------------------------------------
          - name: r22b-arm64-30-doc-group-master
            arch: arm64
            ndk: r22b
            api: 30
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r22b-arm-16-doc-group-master
            arch: arm
            ndk: r22b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r22b-arm64-30-toolchain-doc-group-master
            arch: arm64
            ndk: r22b
            api: 30
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r22b-arm-16-toolchain-doc-group-master
            arch: arm
            ndk: r22b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_master"
# r20b ---------------------------------------------------------------------------
          - name: r20b-arm64-29-doc-group-master
            arch: arm64
            ndk: r20b
            api: 29
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r20b-arm-16-doc-group-master
            arch: arm
            ndk: r20b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r19c ---------------------------------------------------------------------------
          - name: r19c-arm64-28-doc-group-master
            arch: arm64
            ndk: r19c
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r19c-arm-16-doc-group-master
            arch: arm
            ndk: r19c
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm-16-java-toolchain-target-api-16-doc-group-master
            arch: arm
            ndk: r18b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: true
            use_toolchain: true
            target_api: 16
            ace_tao: "doc_group_master"
          - name: r18b-arm64-28-toolchain-doc-group-master
            arch: arm64
            ndk: r18b
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_master"
# doc_group_ace6_tao2 ============================================================
# r23b ---------------------------------------------------------------------------
          - name: r23b-arm64-30-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 30
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-29-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 29
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-28-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-27-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 27
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-26-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 26
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-24-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 24
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-23-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 23
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-22-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 22
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm64-21-doc-group-ace6-tao2
            arch: arm64
            ndk: r23b
            api: 21
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm-20-doc-group-ace6-tao2
            arch: arm
            ndk: r23b
            api: 20
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm-19-doc-group-ace6-tao2
            arch: arm
            ndk: r23b
            api: 19
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm-18-doc-group-ace6-tao2
            arch: arm
            ndk: r23b
            api: 18
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm-17-doc-group-ace6-tao2
            arch: arm
            ndk: r23b
            api: 17
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r23b-arm-16-doc-group-ace6-tao2
            arch: arm
            ndk: r23b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
# r19c ---------------------------------------------------------------------------
          - name: r19c-arm64-28-doc-group-ace6-tao2
            arch: arm64
            ndk: r19c
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r19c-arm-16-doc-group-ace6-tao2
            arch: arm
            ndk: r19c
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm64-28-toolchain-doc-group-ace6-tao2
            arch: arm64
            ndk: r18b
            api: 28
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r18b-arm-16-toolchain-doc-group-ace6-tao2
            arch: arm
            ndk: r18b
            api: 16
            os: "ubuntu-22.04"
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
