name: matrix

on:
  push:
    branches:
      - '**'
      - '!no-gha/**'
  schedule:
    - cron: "0 3 * * 5"
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    # TODO: Figure out a way let the matrix cases define the environment variables
    env:
      name: ${{ matrix.name }}
      arch: ${{ matrix.arch }}
      ndk: ${{ matrix.ndk }}
      api: ${{ matrix.api }}
      use_toolchain: ${{ matrix.use_toolchain }}
      ace_tao: ${{ matrix.ace_tao }}
      use_security: ${{ matrix.use_security }}
      use_java: ${{ matrix.use_java }}
      target_api: ${{ matrix.target_api }}

    steps:
    - name: Check out this repo
      uses: actions/checkout@v5

    - name: Print the Equivalent settings.sh
      # For Quickly Reproducing Failing CI Builds
      run: |
        bash print_settings.sh

    - name: Install Python 2
      if: ${{ matrix.install_python2 }}
      run: |
        sudo apt install python2

    - name: Get NDK and Toolchain
      run: |
        bash get_ndk.sh
        bash get_toolchain.sh
        # This is an extra check for files in the NDK we need to know about.
        # This is not part of run.sh
        bash assert_ndk_files.sh

    - name: Get SDK
      if: ${{ matrix.use_java }}
      run: |
        bash get_sdk.sh

    - name: Get Xerces
      if: ${{ matrix.use_security }}
      run: |
        bash get_xerces.sh

    - name: Get OpenSSL
      if: ${{ matrix.use_security }}
      run: |
        bash get_openssl.sh

    - name: Get ACE/TAO and OpenDDS
      run: |
        bash get_ace_tao.sh
        bash get_opendds.sh

    - name: Use GCC problem matcher
      uses: ammaraskar/gcc-problem-matcher@0.3.0

    - name: Configure and Build Xerces
      if: ${{ matrix.use_security }}
      run: |
        bash build_xerces.sh

    - name: Configure and Build OpenSSL
      if: ${{ matrix.use_security }}
      run: |
        bash build_openssl.sh

    - name: Configure ACE/TAO and OpenDDS
      run: bash configure.sh

    - name: Show Build Config
      run: perl OpenDDS/tools/scripts/show_build_config.pl

    - name: Build ACE/TAO and OpenDDS
      run: bash build.sh

    strategy:
      fail-fast: false
      matrix:
        include:
# BEGIN MATRIX
# This part is generated by matrix.py
# doc_group_master ===============================================================
# r28c ---------------------------------------------------------------------------
          - name: r28c-arm64-30-security-java-doc-group-master
            arch: arm64
            ndk: r28c
            api: 30
            os: "ubuntu-22.04"
            install_python2: false
            use_security: true
            use_java: true
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-29-doc-group-master
            arch: arm64
            ndk: r28c
            api: 29
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-28-doc-group-master
            arch: arm64
            ndk: r28c
            api: 28
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-27-doc-group-master
            arch: arm64
            ndk: r28c
            api: 27
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-26-doc-group-master
            arch: arm64
            ndk: r28c
            api: 26
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-24-doc-group-master
            arch: arm64
            ndk: r28c
            api: 24
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-23-doc-group-master
            arch: arm64
            ndk: r28c
            api: 23
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-22-doc-group-master
            arch: arm64
            ndk: r28c
            api: 22
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r28c-arm64-21-security-java-doc-group-master
            arch: arm64
            ndk: r28c
            api: 21
            os: "ubuntu-22.04"
            install_python2: false
            use_security: true
            use_java: true
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r27c ---------------------------------------------------------------------------
          - name: r27c-arm64-30-doc-group-master
            arch: arm64
            ndk: r27c
            api: 30
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r27c-arm64-21-doc-group-master
            arch: arm64
            ndk: r27c
            api: 21
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r23c ---------------------------------------------------------------------------
          - name: r23c-arm64-30-doc-group-master
            arch: arm64
            ndk: r23c
            api: 30
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
          - name: r23c-arm-16-doc-group-master
            arch: arm
            ndk: r23c
            api: 16
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_master"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm-16-java-toolchain-target-api-16-doc-group-master
            arch: arm
            ndk: r18b
            api: 16
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: true
            use_toolchain: true
            target_api: 16
            ace_tao: "doc_group_master"
          - name: r18b-arm64-28-toolchain-doc-group-master
            arch: arm64
            ndk: r18b
            api: 28
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_master"
# doc_group_ace6_tao2 ============================================================
# r28c ---------------------------------------------------------------------------
          - name: r28c-arm64-30-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 30
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-29-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 29
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-28-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 28
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-27-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 27
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-26-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 26
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-24-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 24
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-23-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 23
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-22-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 22
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r28c-arm64-21-doc-group-ace6-tao2
            arch: arm64
            ndk: r28c
            api: 21
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
# r21e ---------------------------------------------------------------------------
          - name: r21e-arm64-29-doc-group-ace6-tao2
            arch: arm64
            ndk: r21e
            api: 29
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r21e-arm-16-doc-group-ace6-tao2
            arch: arm
            ndk: r21e
            api: 16
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: false
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
# r18b ---------------------------------------------------------------------------
          - name: r18b-arm64-28-toolchain-doc-group-ace6-tao2
            arch: arm64
            ndk: r18b
            api: 28
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
          - name: r18b-arm-16-toolchain-doc-group-ace6-tao2
            arch: arm
            ndk: r18b
            api: 16
            os: "ubuntu-22.04"
            install_python2: false
            use_security: false
            use_java: false
            use_toolchain: true
            target_api: 30
            ace_tao: "doc_group_ace6_tao2"
